/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_FLEET_ADAPTER__SCHEMAS__PLACE
#define RMF_FLEET_ADAPTER__SCHEMAS__PLACE

#include <nlohmann/json.hpp>

namespace rmf_fleet_adapter {
namespace schemas {

static const nlohmann::json place =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_ros2/main/rmf_fleet_adapter/schemas/place.json",
  "title": "Place Description",
  "description": "Description of a place that the robot can go to",
  "oneOf": [
    {
      "$ref": "#/$defs/waypoint"
    },
    {
      "type": "object",
      "properties": {
        "waypoint": { "$ref": "#/$defs/waypoint" },
        "orientation": { "type": "number" }
      },
      "required": ["waypoint"]
    }
  ],
  "$defs": {
    "waypoint": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "integer",
          "minimum": 0
        }
      ]
    }
  }
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_fleet_adapter

#endif // RMF_FLEET_ADAPTER__SCHEMAS__PLACE
