/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_FLEET_ADAPTER__SCHEMAS__PRIORITY_DESCRIPTION__BINARY
#define RMF_FLEET_ADAPTER__SCHEMAS__PRIORITY_DESCRIPTION__BINARY

#include <nlohmann/json.hpp>

namespace rmf_fleet_adapter {
namespace schemas {

static const nlohmann::json priority_description__binary =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_ros2/main/rmf_fleet_adapter/schemas/priority_description__binary.json",
  "title": "Binary Priority Description",
  "description": "Describes the priority of a task as a binary",
  "type": "object",
  "properties": {
      "type": { "type": "string" },
      "value": { "type": "integer", "minimum": 0, "maximum": 1 }
  },
  "required": ["type", "value"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_fleet_adapter

#endif // RMF_FLEET_ADAPTER__SCHEMAS__PRIORITY_DESCRIPTION__BINARY
