/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_FLEET_ADAPTER__SCHEMAS__TASK_DESCRIPTION__DELIVERY
#define RMF_FLEET_ADAPTER__SCHEMAS__TASK_DESCRIPTION__DELIVERY

#include <nlohmann/json.hpp>

namespace rmf_fleet_adapter {
namespace schemas {

static const nlohmann::json task_description__delivery =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_ros2/main/rmf_fleet_adapter/schemas/task_description__delivery.json",
  "title": "Delivery Task Description",
  "description": "Description for a simple delivery task category",
  "type": "object",
  "properties": {
    "pickup": { "$ref": "event_description__pickup.json" },
    "dropoff": { "$ref": "event_description__dropoff.json" }
  },
  "required": ["pickup", "dropoff"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_fleet_adapter

#endif // RMF_FLEET_ADAPTER__SCHEMAS__TASK_DESCRIPTION__DELIVERY
