/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_FLEET_ADAPTER__SCHEMAS__TASK_DESCRIPTION__PATROL
#define RMF_FLEET_ADAPTER__SCHEMAS__TASK_DESCRIPTION__PATROL

#include <nlohmann/json.hpp>

namespace rmf_fleet_adapter {
namespace schemas {

static const nlohmann::json task_description__patrol =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_ros2/main/rmf_fleet_adapter/schemas/task_description__patrol.json",
  "title": "Patrol Task Description",
  "description": "Description of a patrolling task",
  "type": "object",
  "properties": {
    "places": {
      "description": "A list of which places to patrol between",
      "type": "array",
      "items": { "$ref": "place.json" }
    },
    "rounds": {
      "description": "How many times the patrol should be performed. By default this is 1.",
      "type": "integer",
      "minimum": 1
    }
  },
  "required": ["places"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_fleet_adapter

#endif // RMF_FLEET_ADAPTER__SCHEMAS__TASK_DESCRIPTION__PATROL
