/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__DISPATCH_TASK_REQUEST
#define RMF_API_MSGS__SCHEMAS__DISPATCH_TASK_REQUEST

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json dispatch_task_request =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/dispatch_task_request.json",
  "title": "Dispatch Task Request",
  "description": "Request that a task be dispatched to the best available fleet",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a task dispatch request",
      "type": "string",
      "enum": ["dispatch_task_request"]
    },
    "request": { "$ref": "task_request.json" }
  },
  "required": ["type", "request"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__DISPATCH_TASK_REQUEST
