/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__DISPATCH_TASK_RESPONSE
#define RMF_API_MSGS__SCHEMAS__DISPATCH_TASK_RESPONSE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json dispatch_task_response =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/dispatch_task_response.json",
  "title": "Task Dispatch Response",
  "description": "Response to a task dispatch request",
  "type": "object",
  "oneOf": [
    {
      "properties": {
        "success": { "type": "boolean", "enum": [true] },
        "state": { "$ref": "task_state.json" }
      },
      "required": ["success", "state"]
    },
    {
      "properties": {
        "success": { "type": "boolean", "enum": [false] },
        "errors": {
          "description": "Any error messages explaining why the request failed",
          "type": "array",
          "items": { "$ref": "error.json" }
        }
      }
    }
  ]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__DISPATCH_TASK_RESPONSE
