/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__FLEET_LOG_UPDATE
#define RMF_API_MSGS__SCHEMAS__FLEET_LOG_UPDATE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json fleet_log_update =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/fleet_log_update.json",
  "title": "Task Event Log Update",
  "description": "Update for the log of a task. These new entries should be appended to any log entries that already existed for the fleet, ignoring any with a duplicate `seq` value.",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a fleet log update",
      "type": "string",
      "enum": ["fleet_log_update"]
    },
    "data": {"$ref": "fleet_log.json" }
  },
  "required": ["type", "data"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__FLEET_LOG_UPDATE
