/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__FLEET_STATE
#define RMF_API_MSGS__SCHEMAS__FLEET_STATE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json fleet_state =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/fleet_state.json",
  "title": "Fleet State",
  "description": "The state of a fleet",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "robots": {
      "description": "A dictionary of the states of the robots that belong to this fleet",
      "type": "object",
      "additionalProperties": { "$ref": "robot_state.json" }
    }
  }
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__FLEET_STATE
