/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__FLEET_STATE_UPDATE
#define RMF_API_MSGS__SCHEMAS__FLEET_STATE_UPDATE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json fleet_state_update =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/fleet_state_update.json",
  "title": "Fleet State Update",
  "description": "Update for the state of a fleet",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a fleet state update",
      "type": "string",
      "enum": ["fleet_state_update"]
    },
    "data": {
      "$ref": "fleet_state.json"
    }
  },
  "required": ["type", "data"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__FLEET_STATE_UPDATE
