/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__INTERRUPT_TASK_REQUEST
#define RMF_API_MSGS__SCHEMAS__INTERRUPT_TASK_REQUEST

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json interrupt_task_request =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/interrupt_task_request.json",
  "title": "Task Interruption Request",
  "description": "Ask for a task to be interrupted. An interrupted task will resume its task later when a resume_task_requested is sent.",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a task interruption request",
      "type": "string",
      "enum": ["interrupt_task_request"]
    },
    "task_id": {
      "description": "Specify the task ID to interrupt",
      "type": "string"
    },
    "labels": {
      "description": "Labels to describe the purpose of the interruption, items can be a single value like `dashboard` or a key-value pair like `app=dashboard`, in the case of a single value, it will be interpreted as a key-value pair with an empty string value.",
      "type": "array",
      "items": { "type": "string" }
    }
  },
  "required": ["type", "task_id"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__INTERRUPT_TASK_REQUEST
