/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__INTERRUPT_TASK_RESPONSE
#define RMF_API_MSGS__SCHEMAS__INTERRUPT_TASK_RESPONSE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json interrupt_task_response =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/interrupt_task_response.json",
  "title": "Task Interruption Response",
  "description": "Response to a request for a task to be interrupted",
  "$ref": "token_response.json"
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__INTERRUPT_TASK_RESPONSE
