/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__LOCATION_2D
#define RMF_API_MSGS__SCHEMAS__LOCATION_2D

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json location_2D =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/location_2D.json",
  "title": "Location 2D",
  "description": "A robot's location using 2D coordinates",
  "type": "object",
  "properties": {
    "map": { "type": "string" },
    "x": { "type": "number" },
    "y": { "type": "number" },
    "yaw": { "type": "number" }
  },
  "required": ["map", "x", "y", "yaw"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__LOCATION_2D
