/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__REWIND_TASK_REQUEST
#define RMF_API_MSGS__SCHEMAS__REWIND_TASK_REQUEST

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json rewind_task_request =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/rewind_task_request.json",
  "title": "Task Rewind Request",
  "description": "Ask for a task to rewind itself to an earlier phase.",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a task rewind request",
      "type": "string",
      "enum": ["rewind_task_request"]
    },
    "task_id": {
      "description": "Specify the ID of the task that should rewind",
      "type": "string"
    },
    "phase_id": {
      "description": "Specify the phase that should be rewound to. The task will restart at the beginning of this phase.",
      "type": "integer",
      "minimum": 0
    }
  },
  "required": ["type", "task_id", "phase_id"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__REWIND_TASK_REQUEST
