/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__ROBOT_COMMISSION_RESPONSE
#define RMF_API_MSGS__SCHEMAS__ROBOT_COMMISSION_RESPONSE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json robot_commission_response =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/robot_commission_response.json",
  "title": "Robot Commission Response",
  "description": "Response to a robot commission request",
  "type": "object",
  "properties": {
    "commission": { "$ref": "#/$defs/result" },
    "pending_dispatch_tasks_policy": { "$ref": "#/$defs/result" },
    "pending_direct_tasks_policy": { "$ref": "#/$defs/result" }
  },
  "required": ["commission"],
  "$defs": {
    "result": {
      "oneOf": [
        {
          "properties": {
            "success": { "type": "boolean", "enum": [true] }
          },
          "required": ["success"]
        },
        {
          "properties": {
            "success": { "type": "boolean", "enum": [false] },
            "errors": {
              "description": "Any error messages explaining why the request failed",
              "type": "array",
              "items": { "$ref": "error.json" }
            }
          },
          "required": ["success"]
        }
      ]
    }
  }
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__ROBOT_COMMISSION_RESPONSE
