/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__TASK_DISCOVERY_REQUEST
#define RMF_API_MSGS__SCHEMAS__TASK_DISCOVERY_REQUEST

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json task_discovery_request =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/task_discovery_request.json",
  "title": "Task Discovery Request",
  "description": "Ask for tasks that can be performed by the fleets",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a task discovery request",
      "type": "string",
      "enum": ["task_discovery_request"]
    }
  },
  "required": ["type"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__TASK_DISCOVERY_REQUEST
