/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__TASK_LOG_REQUEST
#define RMF_API_MSGS__SCHEMAS__TASK_LOG_REQUEST

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json task_log_request =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/task_log_request.json",
  "title": "Task Log Request",
  "description": "Request the event log for a task",
  "type": "object",
  "properties": {
    "type": {
      "description": "Indicate that this is a task log request",
      "type": "string",
      "enum": ["task_log_request"]
    },
    "task_id": {
      "description": "Specify the ID of the task whose log should be fetched",
      "type": "string"
    }
  },
  "required": ["type", "task_id"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__TASK_LOG_REQUEST
