/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__TRANSFORMATION_2D
#define RMF_API_MSGS__SCHEMAS__TRANSFORMATION_2D

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json transformation_2D =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/transformation_2D.json",
  "title": "Transformation 2D",
  "description": "Transformation between 2 maps",
  "type": "object",
  "properties": {
    "target_map": { "type": "string" },
    "ref_map": { "type": "string" },
    "x": { "type": "number" },
    "y": { "type": "number" },
    "yaw": { "type": "number" },
    "scale": { "type": "number" }
  },
  "required": ["target_map", "ref_map", "x", "y", "yaw", "scale"]
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__TRANSFORMATION_2D
