/*
 * This file is automatically generated by the build system of 
 *
 * Automatically generated files do not have a copyright
 */

#ifndef RMF_API_MSGS__SCHEMAS__UNDO_SKIP_PHASE_RESPONSE
#define RMF_API_MSGS__SCHEMAS__UNDO_SKIP_PHASE_RESPONSE

#include <nlohmann/json.hpp>

namespace rmf_api_msgs {
namespace schemas {

static const nlohmann::json undo_skip_phase_response =
R"raw_schema(
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/open-rmf/rmf_api_msgs/main/rmf_api_msgs/schemas/undo_phase_skip_response.json",
  "title": "Undo Phase Skip Response",
  "description": "Response to an undo phase skip request",
  "$ref": "simple_response.json"
}
)raw_schema"_json;

} // namespace schemas
} // namespace rmf_api_msgs

#endif // RMF_API_MSGS__SCHEMAS__UNDO_SKIP_PHASE_RESPONSE
